# Generated by Django 3.2.3 on 2021-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTable2330',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_2330',
                'managed': False,
            },
        ),
    ]
